[project]
name = "csv-to-chart"
version = "0.1.0"
description = "A web application that converts CSV data to charts using AI"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "Flask",
    "pandas",
    "openai",
    "matplotlib",
    "requests",
]
